import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Globe2, MapPin, Search, Users } from 'lucide-react';

const FALLBACK = [['MX','México','Americas','Ciudad de México',130861007],['AR','Argentina','Americas','Buenos Aires',45808747],['BR','Brasil','Americas','Brasília',203080756],['CA','Canadá','Americas','Ottawa',40097761],['US','Estados Unidos','Americas','Washington, D.C.',334914895],['ES','España','Europe','Madrid',48619695],['FR','Francia','Europe','París',68373433],['DE','Alemania','Europe','Berlín',83555000],['IT','Italia','Europe','Roma',58989749],['JP','Japón','Asia','Tokio',124516650],['IN','India','Asia','Nueva Delhi',1428627663],['AU','Australia','Oceania','Canberra',26974026]].map(([cca2,name,region,capital,population])=>({cca2,name:{common:name},region,capital:[capital],population,flags:{svg:`https://flagcdn.com/${cca2.toLowerCase()}.svg`}}));

export default function RestCountriesView(){
 const [countries,setCountries]=useState([]);const [loading,setLoading]=useState(true);const [notice,setNotice]=useState('');const [search,setSearch]=useState('');
 const request=async()=>{setLoading(true);setNotice('');try{const r=await fetch('https://restcountries.com/v3.1/all?fields=name,flags,capital,region,population,cca2');if(!r.ok)throw new Error();const d=await r.json();if(!Array.isArray(d))throw new Error();setCountries(d.sort((a,b)=>a.name.common.localeCompare(b.name.common)))}catch{setCountries(FALLBACK);setNotice('Mostrando catálogo local porque el servicio en vivo no respondió.')}finally{setLoading(false)}};
 useEffect(()=>{fetch('https://restcountries.com/v3.1/all?fields=name,flags,capital,region,population,cca2').then(r=>{if(!r.ok)throw new Error();return r.json()}).then(d=>{if(!Array.isArray(d))throw new Error();setCountries(d.sort((a,b)=>a.name.common.localeCompare(b.name.common)))}).catch(()=>{setCountries(FALLBACK);setNotice('Mostrando catálogo local porque el servicio en vivo no respondió.')}).finally(()=>setLoading(false))},[]);
 const filtered=useMemo(()=>countries.filter(c=>`${c.name.common} ${c.region}`.toLowerCase().includes(search.toLowerCase())).slice(0,24),[countries,search]);
 return <main className="countries-page"><nav className="api-subnav"><Link to="/"><ArrowLeft size={16}/> Volver al atlas</Link><span>REST COUNTRIES / {countries.length||'—'}</span></nav><section className="countries-wrap"><header className="countries-head"><div><small>DIRECTORIO GEOGRÁFICO</small><h1>El mundo,<br/><em>país por país.</em></h1></div><label><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar país o región..."/></label></header>
 {loading&&<div className="api-state"><div className="spinner"/>Cargando países...</div>}{notice&&<div className="country-notice"><Globe2 size={14}/><span>{notice}</span><button onClick={request}>Reconectar</button></div>}
 {!loading&&<div className="country-grid">{filtered.map((c,i)=><article className="country-card" key={c.cca2} style={{'--delay':`${Math.min(i,12)*35}ms`}}><div className="flag-wrap"><img src={c.flags.svg||c.flags.png} alt={`Bandera de ${c.name.common}`}/><span>{c.cca2}</span></div><div className="country-copy"><small>{c.region}</small><h2>{c.name.common}</h2><div><span><MapPin size={13}/>{c.capital?.[0]||'Sin capital'}</span><span><Users size={13}/>{c.population.toLocaleString('es-MX')}</span></div></div></article>)}</div>}{!loading&&!filtered.length&&<div className="api-state">No hay países que coincidan con “{search}”.</div>}
 </section></main>;
}
