import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Cloud, Droplets, KeyRound, MapPin, Search, Thermometer, Wind } from 'lucide-react';
import RainBackground from '../components/ui/RainBackground';
import MistBackground from '../components/ui/MistBackground';

export default function WeatherView(){
 const [city,setCity]=useState('');const [apiKey,setApiKey]=useState('');const [weather,setWeather]=useState(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
 const hour=new Date().getHours();const period=hour<7||hour>19?'night':hour<12?'morning':'day';
 const submit=async(e)=>{e.preventDefault();if(!city||!apiKey){setError('Ingresa una ciudad y tu API Key');return}setLoading(true);setError('');try{const r=await fetch(`https://api.openweathermap.org/data/2.5/weather?q=${encodeURIComponent(city)}&appid=${apiKey}&units=metric&lang=es`);if(!r.ok)throw new Error('Ciudad no encontrada o API Key inválida');setWeather(await r.json())}catch(err){setError(err.message)}finally{setLoading(false)}};
 const demo=()=>setWeather({name:'Ciudad de México',sys:{country:'MX'},weather:[{description:'lluvia ligera',icon:'10d',main:'Rain'}],main:{temp:19,feels_like:18,humidity:78},wind:{speed:4.2}});
 return <main className={`weather-page ${weather?period:'idle'}`}><MistBackground/><RainBackground intensity={260} speed={.72} angle={8}><nav className="api-subnav"><Link to="/"><ArrowLeft size={16}/> Volver al atlas</Link><span>OPENWEATHER / LIVE</span></nav><section className="weather-layout">
  {!weather?<div className="weather-intro weather-intro-centered"><small>CLIMA GLOBAL EN TIEMPO REAL</small><h1>El clima,<br/><em>ahora mismo.</em></h1><p>Selecciona una ciudad y observa cómo cambia la atmósfera de la experiencia.</p><form onSubmit={submit}><label><KeyRound size={15}/><input value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="Tu API Key de OpenWeather"/></label><label><MapPin size={15}/><input value={city} onChange={e=>setCity(e.target.value)} placeholder="Ciudad de México, Madrid..."/><button disabled={loading}>{loading?<div className="mini-spinner"/>:<Search size={17}/>}</button></label>{error&&<p className="weather-error">{error}</p>}<button type="button" className="weather-demo" onClick={demo}>Ver experiencia con datos de prueba</button></form></div>:
  <div className="weather-result"><button className="weather-reset" onClick={()=>setWeather(null)}>← Consultar otra ciudad</button><div className="liquid-weather"><div className="liquid-shine"/><div className="weather-place"><span><MapPin size={15}/>{weather.name}, {weather.sys.country}</span><time>{new Date().toLocaleTimeString('es-MX',{hour:'2-digit',minute:'2-digit'})}</time></div><div className="weather-main"><div><strong>{Math.round(weather.main.temp)}°</strong><p>{weather.weather[0].description}</p></div><img src={`https://openweathermap.org/img/wn/${weather.weather[0].icon}@4x.png`} alt={weather.weather[0].description}/></div><div className="weather-stats"><span><Thermometer/>Sensación<b>{Math.round(weather.main.feels_like)}°</b></span><span><Droplets/>Humedad<b>{weather.main.humidity}%</b></span><span><Wind/>Viento<b>{weather.wind?.speed||'—'} m/s</b></span><span><Cloud/>Estado<b>{weather.weather[0].main||'Actual'}</b></span></div></div></div>}
 </section></RainBackground></main>;
}
